version: 2
jobs:
  build:
     docker:
       - image: circleci/python:3.7-buster-node-browsers
     steps:
       - checkout
       - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U "pip>=18.0, <19.0" "setuptools>=38.0, <39.0" wheel
       - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "src/requirements.txt" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
       - run:
          name: Force no-caching for master or develop
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]; then
              rm -r ~/project/venv/
              python3 -m venv venv
              . venv/bin/activate
              pip install -U "pip>=18.0, <19.0" "setuptools>=38.0, <39.0" wheel
            fi
       - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r src/requirements.txt -U
       - save_cache:
          paths:
            - ~/project/venv/
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "src/requirements.txt" }}
       - run:
          name: Run flake8, isort, and black
          command: |
            . venv/bin/activate
            kedro lint --check-only
       - run:
          name: Run tests
          command: |
            . venv/bin/activate
            kedro test
       - run:
          name: Package the project
          command: |
            . venv/bin/activate
            kedro package
